set_property SRC_FILE_INFO {cfile:/home/cod/Desktop/prj5_1/v1/prj5-cpu-opt-harvardchen/hardware/constraints/mips_cpu_simu.xdc rfile:../../constraints/mips_cpu_simu.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property package_pin C4 [get_ports mips_cpu_clk]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property package_pin B8 [get_ports mips_cpu_reset]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property package_pin C8 [get_ports mips_cpu_pc_sig]
